### ISSUE TITLE
Looking Glass Host (Windows) crashes immediately when there is more than one IVSHMEM device - apparently ignores .ini configuration

### ISSUE THREAD

**Issue by JaneSmith** [gnif/LookingGlass#283]
Host CPU: AMD Ryzen 3900X.
Host GPU: AMD Radeon RX 550.
Guest GPU: AMD Radeon RX 5700 XT.
Host Kernel version: 5.6.14-300.fc32.x86_64
Host QEMU version: 4.2.0-7.fc32

The problem occurs when attempting to start `looking-glass-host.exe`. It simply crashes immediately without actually starting up.

No `looking-glass-host.dmp` file seems to exist anywhere. However, there is a `looking-glass-host.txt` file located in `%LocalAppData%\Temp`. It contains the following:

```
2552193554 [I]           platform.c:292  | app_init                       | System timer resolution: 48.82 ns
2552194557 [I]                app.c:402  | app_main                       | Looking Glass Host (B2-rc2-0-gd579705b10)
2552202318 [I]                app.c:412  | app_main                       | IVSHMEM Size     : 2 MiB
2552203074 [I]                app.c:413  | app_main                       | IVSHMEM Address  : 0x2DD0000
2552203856 [I]                app.c:414  | app_main                       | Max Pointer Size : 64 KiB
2552204604 [I]                app.c:415  | app_main                       | KVMFR Version    : 1
2552205215 [I]                app.c:462  | app_main                       | Max Frame Size   : 0 MiB
2552205493 [I]                app.c:477  | app_main                       | Trying           : NVFBC (NVidia Frame Buffer Capture)
[E]          wrapper.cpp:60   | NvFBCInit                      | Failed to load NvFBC64.dll: 0x0000007e (The specified module could not be found.)
2552206558 [I]                app.c:477  | app_main                       | Trying           : DXGI
2552228707 [I]               dxgi.c:376  | dxgi_init                      | Device Descripion: AMD Radeon RX 5700 XT
2552229029 [I]               dxgi.c:377  | dxgi_init                      | Device Vendor ID : 0x1002
2552229306 [I]               dxgi.c:378  | dxgi_init                      | Device Device ID : 0x731f
2552229587 [I]               dxgi.c:379  | dxgi_init                      | Device Video Mem : 8151 MiB
2552229869 [I]               dxgi.c:380  | dxgi_init                      | Device Sys Mem   : 0 MiB
2552230137 [I]               dxgi.c:381  | dxgi_init                      | Shared Sys Mem   : 8191 MiB
2552230424 [I]               dxgi.c:382  | dxgi_init                      | Feature Level    : 0xb100
2552230704 [I]               dxgi.c:383  | dxgi_init                      | Capture Size     : 3840 x 2160
2552230998 [I]               dxgi.c:384  | dxgi_init                      | AcquireLock      : disabled
2552232291 [I]               dxgi.c:487  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
2552232928 [I]                app.c:245  | captureStart                   | Using            : DXGI
2552233200 [E]                app.c:250  | captureStart                   | Maximum frame size of 33177600 bytes excceds maximum space available
```

From this error log, it appears that Looking Glass is trying to use my 2 MiB IVSHMEM device instead of the correct 128 MiB device that I have defined on the virtual machine. Below is the relevant portion of my VM configuration:

```
<shmem name="looking-glass">
  <model type="ivshmem-plain"/>
  <size unit="M">128</size>
  <address type="pci" domain="0x0000" bus="0x08" slot="0x02" function="0x0"/>
</shmem>
<shmem name="scream-ivshmem">
  <model type="ivshmem-plain"/>
  <size unit="M">2</size>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x0b" function="0x0"/>
</shmem>
```

I have seen issue #190, in which the comments state that Looking Glass can be told which IVSHMEM device to use via a `looking-glass-host.ini` file. However, I already have that file in the same folder as `looking-glass-host.exe`, containing a configuration along the lines of:

```
[os]
shmDevice=1
```

I have tried changing the number to 0, 1, 2, 3. Nothing makes any difference. It seems as if Looking Glass just completely ignores this file and insists on trying to grab the 2 MiB device.

So now I'm just totally stuck and am unable to use this software. I have already seen the comments saying that Scream over IVSHMEM is supposedly terrible and should not be used in the first place (albeit without any data to show this, and despite it working perfectly for me), but I can't get the networked version of Scream working anyway, so I'm stuck using the IVSHMEM version of it. I also believe this Looking Glass issue should be fixed as there could be other reasons to use a second IVSHMEM device too.

Any help would be appreciated.

**Comment by gnif** [comment]
This is not an LG issue but a result of the ordering that windows enumerate the IVSHMEM devices, which is random and there is nothing that can be done about this.

> I have tried changing the number to 0, 1, 2, 3. Nothing makes any difference. It seems as if Looking Glass just completely ignores this file and insists on trying to grab the 2 MiB device.

It may not be finding the file on disk, I am about to push in a change that should resolve this.

>  Scream over IVSHMEM is supposedly terrible and should not be used in the first place (albeit without any data to show this, and despite it working perfectly for me)

Working perfectly is not working optimally. It uses CPU polling to determine when new data is available and consumes a ton of CPU resources as a result of a broken and useless implementation. No data is needed, all one needs to do is review the source.

Instead of using Scream why not just use the native audio support built into Qemu? It works far better, requires no client drivers, provides lower latency and CPU usage. With QEMU 5.1 there will be a Jack audiodev plugin also to allow you to do some pretty fancy stuff you simply can't do with Scream.

**Comment by gnif** [comment]
>  I am about to push in a change that should resolve this.

67dec216d2b11a7d6948b3dc047026330448ee63

**Comment by JaneSmith** [comment]
Thanks a lot for the quick reply and commit. I just gave it a go, and it seems like there's progress, but it's still not working for me.

When I run `looking-glass-host.exe` from the Windows Command Prompt, the output shows that it's looking for the configuration file at the correct location, and then loads it. That's more than it did before - it used to give me no output whatsoever. So it's apparently finding the configuration file properly now.

However, it still seems to be using the 2 MiB IVSHMEM device. Again, no matter whether I try 0, 1, or 2 in the config file, the `looking-glass-host.txt` log shows that it's trying to use the 2 MiB one and then failing as it's not large enough. When I start it up, I see the tray icon briefly flicker in the system tray before disappearing. After the Command Prompt output about loading the configuration file, nothing more is output and I just have to forcibly close the application.

Any other ideas? Thanks.

As for QEMU's built-in audio support... Maybe I'm doing something wrong with it, but I've always had crackling sound issues with it, and would also need to change QEMU to run under my standard user, which then caused other issues (although I don't remember what they were). I've also seen many other people on the `/r/vfio` subreddit discussing issues with it's built-in audio support, whilst Scream is simple to set up and seems to work with no perceived problems. It just seems to be a lot more convenient and straightforward to get going.

**Comment by set4812** [comment]
@JaneSmith I have the same problem. There is a workaround for me, run VM, enter device manager inside windows, disable one of IVSHMEM Devices for me is the second one. Run looking glass executable file and next enable disabled device.

**Comment by accumulator** [comment]
Same problem here. Nothing in the logs, and the host is in a crash loop, spamming my system tray with hundreds of looking glass icons

**Comment by gnif** [comment]
Most hitting this issue are trying to use SCREAM over IVSHMEM, as such this is a low priority bug as SCREAM over IVSHMEM is just plain dumb.

**Note: While this setup is possible it is ill-advised, Scream does not benefit from using IVSHMEM in any way, if anything it increases CPU load and latency due to the polling nature of the implementation. Scream operates far better over a vfio-net device which is already a zero-copy data transfer via shared memory. If you however insist on continuing you're on your own if you run into issues.**

If you must use SCREAM, use it over LAN as it was originally intended, see:
https://looking-glass.io/wiki/Using_Scream_over_LAN

If you insist on using SCREAM over IVSHMEM and wasting CPU cycles for no reason see:
https://looking-glass.io/wiki/Using_Scream_over_IVSHMEM

**Comment by accumulator** [comment]
I am using scream, but I moved to multicast via virtio-net a while ago. Unless I missed some remnant of the old ivshmem setup, scream should not be the cause. I double checked the scream registry entry, checked only the 128M looking-glass ivshmem is available to windows, checked the apparmour and filesystem acls for `/dev/shm/looking-glass` and finally uninstalled scream altogether. Not sure what else there is to check. 

Windows event log shows exception code 0xc000001d (illegal instruction). Is that how it fails if there is a conflict with scream ivshmem?

**Comment by gnif** [comment]
Then you have a completely different problem (did you set your CPU to host passthrough)?

**Comment by gnif** [comment]
This issue has been resolved, failure to parse the settings was due to UTF8 bytes windows saves text files with, as well as a failure to use a setting if it was on the last line of the file.
